CREATE TABLE IF NOT EXISTS invoices (
	id SERIAL PRIMARY KEY,
	business_id INTEGER REFERENCES businesses(id) ON DELETE CASCADE,
	amount DECIMAL(10, 2) NOT NULL,
	status VARCHAR(50) DEFAULT 'unpaid',
	due_at TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

