CREATE TABLE IF NOT EXISTS domains (
	id SERIAL PRIMARY KEY,
	business_id INTEGER REFERENCES businesses(id) ON DELETE CASCADE,
	domain_name VARCHAR(255) UNIQUE NOT NULL,
	is_custom BOOLEAN DEFAULT false,
	status VARCHAR(50) DEFAULT 'pending',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

