CREATE TABLE IF NOT EXISTS businesses (
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	name VARCHAR(255) NOT NULL,
	slug VARCHAR(255) UNIQUE NOT NULL,
	description TEXT,
	logo VARCHAR(255),
	industry VARCHAR(255),
	phone VARCHAR(50),
	address VARCHAR(255),
	status VARCHAR(50) DEFAULT 'pending',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

