CREATE TABLE IF NOT EXISTS payments (
	id SERIAL PRIMARY KEY,
	invoice_id INTEGER REFERENCES invoices(id) ON DELETE CASCADE,
	amount DECIMAL(10, 2) NOT NULL,
	payment_method VARCHAR(255),
	transaction_id VARCHAR(255),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

