CREATE TABLE IF NOT EXISTS subscriptions (
	id SERIAL PRIMARY KEY,
	business_id INTEGER REFERENCES businesses(id) ON DELETE CASCADE,
	plan_id INTEGER REFERENCES plans(id) ON DELETE CASCADE,
	status VARCHAR(50) DEFAULT 'active',
	ends_at TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

